version: '3.7'
services:
  web:
    image: nginx:1.19-alpine
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./templates:/etc/nginx/templates
      - ./socket:/run/ciziproblem
    ports:
      - "7777:7777"
    environment:
      - NGINX_HOST=ciziproblem.cz
      - NGINX_PORT=7777
    depends_on:
      - bottle
  bottle:
    build:
      context: .
    volumes:
      - ./socket:/ciziproblem/socket
      - ./log/uwsgi:/var/log/uwsgi
      - ./data/files:/ciziproblem/data/files
    environment:
      TOKEN_GET: "$TOKEN_GET"
      TOKEN_POST: "$TOKEN_POST"
